# Generated by Django 5.2.8 on 2025-11-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.PositiveBigIntegerField()),
                ('employee_name', models.CharField(max_length=255)),
                ('department', models.CharField()),
                ('task_id', models.PositiveBigIntegerField()),
                ('task_name', models.CharField(max_length=255)),
                ('hours_spent', models.PositiveBigIntegerField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('progress', 'Progress'), ('completed', 'Completed')], default='progress')),
            ],
        ),
    ]
