# Generated by Django 5.2.8 on 2025-11-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ew_app', '0003_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('hr', 'HR'), ('marketing', 'Marketing')], default='engineering'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
